### PR TITLE
Fix compilation

### PR DESCRIPTION
**Pull request by diocas**
Aligned the compilation code with upstream (had to finally try to make it work), and now it builds the frontend components as well (these were being skipped).

Changed the name of the folder of the nbextension from "static" to "nbextension" (the Lab extension was inside "labextension", so it makes more sense this way).

Since the extension gets automatically copied to the final destination (and now the build code doesn't include the lab extension together with the Python module by default), I removed the possibility of manually installing it. This part of the code was (and would continue to) crash, since it was relying on the `package.json` file to retrieve the name (which was not necessary, but that's how it was).
I believe none of this is necessary, but we can easily add it back.

Needs testing.

### CODE REVIEW

**Review by etejedor — DISMISSED** [review]

**Comment by etejedor** [comment]
@diocas should we have a look at the failed JavaScript check?

**Comment by camper42** [comment]
maybe 3.0.2 or 3.1.0 release ?

our usage failed with 3.0.1:
`FileNotFoundError: [Errno 2] No such file or directory: '/opt/python/lib/python3.10/site-packages/sparkmonitor/labextension/package.json'`

**Comment by diocas** [comment]
@camper42 we removed version 3.0.1 because of that. This PR should fix the issue. We will tag a new version this Wednesday.
Sorry for the trouble.

**Comment by camper42** [comment]
never mind, thank you very much for your work in support of Lab 4

**Pull request merged**
